### ISSUE TITLE
Issues with helper

### ISSUE THREAD

**Issue by rjhaggart** [jonschlinkert/handlebars-helper-inarray#1]
Hi, i'm trying to get this helper to work.

I've installed the helper, so i can see it in node_modules, i've added my helper files to the assemble helper options, `helpers: ['themes/<%= config.theme %>/tmpl/helpers/helper-inArray.js']`

and i have the following in the helper file:

```
module.exports.register = function(Handlebars) {
    Handlebars.registerHelper('inArray', inArray);
};
```

What am i missing?  I have had problems with the handlebar-helpers also.  Just wondering if this is due to my grunt setup?  I'm loading assemble settings from a separate file using:

```
    var config = {
        pkg: grunt.file.readJSON('package.json'),
        config: grunt.file.readJSON('grunt/config.json')
    };

    require('load-grunt-tasks')(grunt);

    grunt.util._.extend(config, loadConfig('./grunt/options/'));

    grunt.initConfig(config);
```

**Comment by jonschlinkert** [comment]
Sorry for the delay. To get custom helpers to load you have to define them on the options of the assemble task, but the helpers from the handlebars-helpers project are loaded by default. 

Is the `inArray` helper custom or from the handlebars-helpers project? Can you paste the code for it here?

Actually it would probably be most helpful if you could just paste the entire gruntfile, or at least all of the related code, either here or in a gist.

**Comment by rjhaggart** [comment]
Hey Jon, sorry for not responding until now and thanks for getting back to me.  I've create a gist of the gruntfile.  Thanks for your help, assemble is awesome!

https://gist.github.com/rjhaggart/a09a9c13776bc9a2ed8a

**Comment by doowb** [comment]
Closing due to age. If you're still having an issue, please open a new issue with your assemble configuration.
